// Code generated by "stringer -type StatusCode"; DO NOT EDIT

package dimse

import "fmt"

const _StatusCode_name = "StatusSuccessStatusInvalidAttributeValueStatusAttributeListErrorStatusSOPClassNotSupportedStatusInvalidArgumentValueStatusAttributeValueOutOfRangeStatusInvalidObjectInstanceStatusNotAuthorizedStatusUnrecognizedOperationCStoreOutOfResourcesCMoveOutOfResourcesUnableToCalculateNumberOfMatchesCMoveOutOfResourcesUnableToPerformSubOperationsCMoveMoveDestinationUnknownCStoreDataSetDoesNotMatchSOPClassCStoreCannotUnderstandStatusCancelStatusPending"

var _StatusCode_map = map[StatusCode]string{
	0:     _StatusCode_name[0:13],
	262:   _StatusCode_name[13:40],
	263:   _StatusCode_name[40:64],
	274:   _StatusCode_name[64:90],
	277:   _StatusCode_name[90:116],
	278:   _StatusCode_name[116:146],
	279:   _StatusCode_name[146:173],
	292:   _StatusCode_name[173:192],
	529:   _StatusCode_name[192:219],
	42752: _StatusCode_name[219:239],
	42753: _StatusCode_name[239:290],
	42754: _StatusCode_name[290:337],
	43009: _StatusCode_name[337:364],
	43264: _StatusCode_name[364:397],
	49152: _StatusCode_name[397:419],
	65024: _StatusCode_name[419:431],
	65280: _StatusCode_name[431:444],
}

func (i StatusCode) String() string {
	if str, ok := _StatusCode_map[i]; ok {
		return str
	}
	return fmt.Sprintf("StatusCode(%d)", i)
}
