// Code generated by "stringer -type AbortReasonType"; DO NOT EDIT

package pdu

import "fmt"

const (
	_AbortReasonType_name_0 = "AbortReasonNotSpecified"
	_AbortReasonType_name_1 = "AbortReasonUnexpectedPDUAbortReasonUnrecognizedPDUParameterAbortReasonUnexpectedPDUParameterAbortReasonInvalidPDUParameterValue"
)

var (
	_AbortReasonType_index_0 = [...]uint8{0, 23}
	_AbortReasonType_index_1 = [...]uint8{0, 24, 59, 92, 127}
)

func (i AbortReasonType) String() string {
	switch {
	case i == 0:
		return _AbortReasonType_name_0
	case 2 <= i && i <= 5:
		i -= 2
		return _AbortReasonType_name_1[_AbortReasonType_index_1[i]:_AbortReasonType_index_1[i+1]]
	default:
		return fmt.Sprintf("AbortReasonType(%d)", i)
	}
}
