// Code generated by "stringer -type AbortReasonType"; DO NOT EDIT.

package pdu

import "fmt"

const (
	_AbortReasonType_name_0 = "AbortReasonNotSpecifiedAbortUnexpectedPDU"
	_AbortReasonType_name_1 = "AbortUnrecognizedPDUParameterAbortUnexpectedPDUParameterAbortInvalidPDUParameterValue"
)

var (
	_AbortReasonType_index_0 = [...]uint8{0, 23, 41}
	_AbortReasonType_index_1 = [...]uint8{0, 29, 56, 85}
)

func (i AbortReasonType) String() string {
	switch {
	case 0 <= i && i <= 1:
		return _AbortReasonType_name_0[_AbortReasonType_index_0[i]:_AbortReasonType_index_0[i+1]]
	case 3 <= i && i <= 5:
		i -= 3
		return _AbortReasonType_name_1[_AbortReasonType_index_1[i]:_AbortReasonType_index_1[i+1]]
	default:
		return fmt.Sprintf("AbortReasonType(%d)", i)
	}
}
