// Code generated by "stringer -type AbortReasonType"; DO NOT EDIT.

package pdu

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AbortReasonNotSpecified-0]
	_ = x[AbortReasonUnexpectedPDU-2]
	_ = x[AbortReasonUnrecognizedPDUParameter-4]
	_ = x[AbortReasonUnexpectedPDUParameter-5]
	_ = x[AbortReasonInvalidPDUParameterValue-6]
}

const (
	_AbortReasonType_name_0 = "AbortReasonNotSpecified"
	_AbortReasonType_name_1 = "AbortReasonUnexpectedPDU"
	_AbortReasonType_name_2 = "AbortReasonUnrecognizedPDUParameterAbortReasonUnexpectedPDUParameterAbortReasonInvalidPDUParameterValue"
)

var (
	_AbortReasonType_index_2 = [...]uint8{0, 35, 68, 103}
)

func (i AbortReasonType) String() string {
	switch {
	case i == 0:
		return _AbortReasonType_name_0
	case i == 2:
		return _AbortReasonType_name_1
	case 4 <= i && i <= 6:
		i -= 4
		return _AbortReasonType_name_2[_AbortReasonType_index_2[i]:_AbortReasonType_index_2[i+1]]
	default:
		return "AbortReasonType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
