// Code generated by "stringer -type PresentationContextResult"; DO NOT EDIT

package pdu

import "fmt"

const _PresentationContextResult_name = "PresentationContextAcceptedPresentationContextUserRejectionPresentationContextProviderRejectionNoReasonPresentationContextProviderRejectionAbstractSyntaxNotSupportedPresentationContextProviderRejectionTransferSyntaxNotSupported"

var _PresentationContextResult_index = [...]uint8{0, 27, 59, 103, 165, 227}

func (i PresentationContextResult) String() string {
	if i >= PresentationContextResult(len(_PresentationContextResult_index)-1) {
		return fmt.Sprintf("PresentationContextResult(%d)", i)
	}
	return _PresentationContextResult_name[_PresentationContextResult_index[i]:_PresentationContextResult_index[i+1]]
}
