// Code generated by "stringer -type SourceType"; DO NOT EDIT.

package pdu

import "fmt"

const _SourceType_name = "SourceULServiceUserSourceULServiceProviderACSESourceULServiceProviderPresentation"

var _SourceType_index = [...]uint8{0, 19, 46, 81}

func (i SourceType) String() string {
	i -= 1
	if i >= SourceType(len(_SourceType_index)-1) {
		return fmt.Sprintf("SourceType(%d)", i+1)
	}
	return _SourceType_name[_SourceType_index[i]:_SourceType_index[i+1]]
}
